---
- name: Create OpenShift Project hello-world
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    kubeconfig_path: "/root/ocp4/auth/kubeconfig"
    project_name: "uat-infra-tools"

  tasks:
    - name: Ensure required Python packages are installed
      ansible.builtin.package:
        name: python3
        state: present
        
    - name: Ensure required Python packages are installed
      pip:
        name:
          - openshift
          - kubernetes
        state: present

    - name: Verify the project was created (list all namespaces)
      k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        kind: Namespace
      register: ns_info

    - name: Show only the created namespace
      debug:
        msg: "{{ ns_info.resources | map(attribute='metadata.name') | select('equalto', project_name) | list }}"

