---
- name: Create NodeNetworkConfigurationPolicy for OVN-Kubernetes secondary network
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create NodeNetworkConfigurationPolicy object
      k8s:
        state: present
        definition:
          apiVersion: nmstate.io/v1
          kind: NodeNetworkConfigurationPolicy
          metadata:
            name: mapping
          spec:
            nodeSelector:
              node-role.kubernetes.io/worker: ''
            desiredState:
              ovn:
                bridge-mappings:
                - localnet: localnet-network
                  bridge: br-ex
                  state: present

