# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sise-deploy
  namespace: rhce-consulting-vms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sise
  template:
    metadata:
      labels:
        app: sise
    spec:
      containers:
        - name: sise
          image: quay.io/openshiftlabs/simpleservice:0.5.0
          ports:
            - containerPort: 9876
          env:
            - name: SIMPLE_SERVICE_VERSION
              value: "0.9"
---
apiVersion: v1
kind: Service
metadata:
  name: sise-svc
  namespace: rhce-consulting-vms
spec:
  selector:
    app: sise
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9876
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: simple-service
  namespace: rhce-consulting-vms
spec:
  host: simple-service.apps.ocp2.redhat-workshop.in
  path: /info
  port:
    targetPort: 9876
  to:
    kind: Service
    name: sise-svc
    weight: 100
  wildcardPolicy: None

