---
- name: Create NetworkAttachmentDefinition for localnet network
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create NetworkAttachmentDefinition object
      k8s:
        state: present
        definition:
          apiVersion: k8s.cni.cncf.io/v1
          kind: NetworkAttachmentDefinition
          metadata:
            name: localnet-nad
            namespace: default
          spec:
            config: |
              {
                "cniVersion": "0.3.1",
                "name": "localnet-network",
                "type": "ovn-k8s-cni-overlay",
                "topology": "localnet",
                "netAttachDefName": "default/localnet-nad",
                "mtu": 1400,
                "parameters": {
                  "bridge": "br-ex",
                  "netType": "localnet"
                }
              }

