---
- name: Get AAP admin password from OpenShift secret
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    kubeconfig_path: "/root/ocp4/auth/kubeconfig"
    aap_namespace: "aap"
    secret_name: "aap-admin-password"  # typically named this way

  tasks:

    - name: Get the AAP admin password secret
      k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        kind: Secret
        namespace: "{{ aap_namespace }}"
        name: "{{ secret_name }}"
      register: secret_result

    - name: Decode and display the admin password
      vars:
        encoded_password: "{{ secret_result.resources[0].data.password }}"
        decoded_password: "{{ encoded_password | b64decode }}"
      debug:
        msg: "🔐 AAP admin password is: {{ decoded_password }}"
